version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
      target: builder
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - WORKERS=1
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
      - RELOAD=true
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: ["uvicorn", "src.presentation.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge