services:
  app:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
      target: builder
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - WORKERS=1
      - LOG_LEVEL=debug
      - RELOAD=true
      - CACHE_TTL_L1=5
      - COINGECKO_API_KEY=
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: ["uvicorn", "src.presentation.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge