global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'crypto-price-monitor'

scrape_configs:
  - job_name: 'crypto-price-api'
    static_configs:
      - targets: ['app:8001']
        labels:
          service: 'crypto-price-api'
          environment: 'production'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']